# Generated by Django 5.0.6 on 2026-03-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0015_galeria_uuid_alter_banners_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='nombre_persona',
            field=models.CharField(default='Anónimo', max_length=100),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
