# Generated by Django 5.0.6 on 2026-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0016_preguntas_fecha_respuesta_preguntas_nombre_persona_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'ordering': ['orden', '-fecha']},
        ),
        migrations.AddField(
            model_name='preguntas',
            name='es_frecuente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(max_length=300),
        ),
    ]
