# Generated by Django 5.0.6 on 2026-04-15 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0017_delete_banners_alter_preguntas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descripcion_breve',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
