# Generated by Django 5.0.6 on 2026-04-16 04:17

import cross_asistent.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0018_articulos_descripcion_breve_alter_articulos_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=120, upload_to=cross_asistent.models.set_imgBlog_path)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_imagenes', to='cross_asistent.articulos')),
            ],
        ),
    ]
